### ISSUE TITLE
building legend from list of components

### ISSUE THREAD

**Issue by alexcolyer** [agilescientific/striplog#113]
Hi, 

I am trying to build a legend from a list of borehole components. However, I cannot work out how to export the unique components to an array, so that I can build the legend. Can this be done? I have 294 borehole intervals in by database so printing them out is not practical.

A simple example would be:

from striplog import Lexicon, Component
rockDescriptions = ['fine grained Sandstone', 'mudstone', 'coarse grained hard sandstone']
lexicon = Lexicon.default()
components = []

for i in range(len(rockDescriptions)):
    components.append(Component.from_text(rockDescriptions[i], lexicon = lexicon))

uniqueComponents = ?

**Comment by mtb-za** [comment]
One possible approach is to use something like:

    list(set(components))
or

    np.array(set(components))

A `set` is an unordered collection of unique items. Not quite sure that this does what you intend, since there are three unique Components in your code snippet as written, and I am not sure if your example is meant to only have two (sandstone and mudstone).

**Comment by kwinkunks** [comment]
I think this specific issue can be closed, though probably it could be easier to do this sort of thing. I think it's easy to get the random legend that striplog makes, but I'm not sure how easy it is to, say, make that into a csv so you can change it easily.

**Comment by kwinkunks** [comment]
Just checked, I think it would be easy enough.

And the `striplog.unique()` method will get unique (primary) components too, of course.
