### ISSUE TITLE
Sphinx docs broken?

### ISSUE THREAD

**Issue by Connossor** [agilescientific/striplog#115]
It looks like the Sphinx docs might be broken?

The following page is blank
https://striplog.readthedocs.io/en/stable/lexicon.html

![image](https://user-images.githubusercontent.com/22548039/81175709-e4d3a580-8f9b-11ea-897d-cc1a9c0fc75b.png)

**Comment by kwinkunks** [comment]
Thank you! We'll take a look at it ASAP... I'll need to enlist @dfcastap because I have no idea what I'm doing with Sphinx (as you can see!).

FWIW, it's all auto-doc, so you can also check `help(Lexicon)` in the interactive prompt.

**Comment by dfcastap** [comment]
Thanks for the heads up. The auto-docs should be back up now. We're also working on enhancing 
 the documentation with usage examples soon!

**Comment by mtb-za** [comment]
The docs have been completely redone recently, so this should be fixed now. :)

Check https://code.agilescientific.com/striplog/ for the latest.
