### ISSUE TITLE
Broken .plot_graph function?

### ISSUE THREAD

**Issue by ThirstyGeo** [agilescientific/striplog#124]
Based in the API for [NetworkX,](https://networkx.org/documentation/stable//reference/generated/networkx.drawing.nx_pylab.draw_networkx_edges.html) it looks like the 'spline' argument doesn't exist anymore. It should possibly be 'connectionstyle'

Currently doing this

``` m.plot_graph(figsize=(15,15), max_size=2400, edge_labels=True) ```

causes this:

``` TypeError: draw_networkx_edges() got an unexpected keyword argument 'splines' ```

**Comment by kwinkunks** [comment]
I think this was fixed by 952488295b3b27f29825b626bd8911d251fc71b9
