### ISSUE TITLE
Order of intervals can break striplog

### ISSUE THREAD

**Issue by kwinkunks** [agilescientific/striplog#127]
The problem in the `to_log()` function, which is consistently getting the indices (`start_ix`, `stop_ix`, `top_index`, `base_index`) backwards in this dataset. 

I think the problem is that we need to reverse indices when order is 'elevation'.

I think this affects `to_log()` and `fill()` at least.

See https://swung.slack.com/archives/C01FC2V9NVD/p1616330076013100

**Comment by mtb-za** [comment]
@kwinkunks this is resolved as of https://github.com/agile-geoscience/striplog/commit/527fe88aa96062f804668cfabdff768e8dd889d9, yes? Looking to see if I can close this issue.

**Comment by kwinkunks** [comment]
Let's say this is fixed.
