### ISSUE TITLE
Black and white plotting option

### ISSUE THREAD

**Issue by kwinkunks** [agilescientific/striplog#7]
It would be cool to have fills as well as or instead of colours.

Bonus: see #8

**Comment by kwinkunks** [comment]
From v1.0 scoping doc: 

> The use of arbitrary colour tables and some pattern templates. Examples of both will be included for each of the converted datasets. We will attempt to allow completely arbitrary pattern fill, but this requires the native production of SVG files, which we can do in principle via our g3.js library, but this may not be possible in the time available.

**Comment by kwinkunks** [comment]
matplotlib hatches...

https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/hatch.py

Should be able to subclass to have

- other shapes
- random scattering (eg for sandstone)
- dashed hatching

Eg see this example (not sure how great the code is...)

http://stackoverflow.com/questions/17285154/how-to-fill-a-polygon-with-a-custom-hatch-in-matplotlib

**Comment by LukasMosser** [comment]
Would it be possible to include the USGS geology hatches?
I've been looking on whether matplotlib supports hatches from bitmap or some pattern but could only find your above example with the polygon fill.

Here the link to USGS patterns:
http://pubs.usgs.gov/tm/2006/11A02/

**Comment by kwinkunks** [comment]
Great suggestion. I think we can replicate a few of these with matplotlib's usual implementation for hatch fills, which uses paths to draw the elements of the hatch. I was going to work on this now, so I'll have some results shortly.

Mpl's paths are quite similar to the SVG and PS specifications, so it might be possible to use the instructions from the EPS files from USGS to replicate them that way, with a little manipulation in between. This would be preferable to doing it with bitmaps (and as you suggest, that may not even be possible).

**Comment by kwinkunks** [comment]
Commit 932114c09bcb5216a3884b935cc286ef4a443417 contains some custom hatches:

![image](https://cloud.githubusercontent.com/assets/1692372/12894388/c464d728-ce6c-11e5-9a4c-e2aea5c851ad.png)

**Comment by kwinkunks** [comment]
Closing this.

USGS patterns: see #103

Matplotlib hatching: see #140
